# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\x16travelhub.embedding.v1\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"W\n\x1aPreferenceEmbeddingRequest\x12\x11\n\ttrip_type\x18\x01 \x01(\t\x12\x11\n\tinterests\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\"=\n\x14PostEmbeddingRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\"7\n\x11\x45mbeddingResponse\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x12\n\ndimensions\x18\x02 \x01(\x05\x32\xec\x02\n\x10\x45mbeddingService\x12h\n\x11GenerateEmbedding\x12(.travelhub.embedding.v1.EmbeddingRequest\x1a).travelhub.embedding.v1.EmbeddingResponse\x12|\n\x1bGeneratePreferenceEmbedding\x12\x32.travelhub.embedding.v1.PreferenceEmbeddingRequest\x1a).travelhub.embedding.v1.EmbeddingResponse\x12p\n\x15GeneratePostEmbedding\x12,.travelhub.embedding.v1.PostEmbeddingRequest\x1a).travelhub.embedding.v1.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=43
  _globals['_EMBEDDINGREQUEST']._serialized_end=75
  _globals['_PREFERENCEEMBEDDINGREQUEST']._serialized_start=77
  _globals['_PREFERENCEEMBEDDINGREQUEST']._serialized_end=164
  _globals['_POSTEMBEDDINGREQUEST']._serialized_start=166
  _globals['_POSTEMBEDDINGREQUEST']._serialized_end=227
  _globals['_EMBEDDINGRESPONSE']._serialized_start=229
  _globals['_EMBEDDINGRESPONSE']._serialized_end=284
  _globals['_EMBEDDINGSERVICE']._serialized_start=287
  _globals['_EMBEDDINGSERVICE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
